Create database CustomerTrend;
use CustomerTrend;

select count(customer_id) from customertrend.customer_behaviour;
-- Q1. What is the total revenue generated by male vs. female customers?
Select 
      gender,
      sum(purchase_amount)  as "revenue"
from customertrend.customer_behaviour
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select
     Customer_id,
     purchase_amount
from customertrend.customer_behaviour
where discount_applied='Yes' and  purchase_amount >= (Select avg(purchase_amount) from customertrend.customer_behaviour);
     

-- Q3. Which are the top 5 products with the highest average review rating?
Select 
     item_purchased,
     round(avg(review_rating),2) as "Avg_rating"
from customertrend.customer_behaviour
group by item_purchased
order by Avg_rating Desc Limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
Select 
     Shipping_type,
     Round(avg(purchase_amount),2) as Avg_amount
from customertrend.customer_behaviour
where Shipping_type in ('Standard','Express')
group by Shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
Select
     Subscription_status,
     count(Customer_id) as total_customer,
     Avg(purchase_amount) as Avg_amount,
     Sum(purchase_amount) as Total_amount
from customertrend.customer_behaviour
group by Subscription_status
order by Avg_amount,total_amount desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select 
     item_purchased,
     round(100*sum(Case
             when discount_applied = 'Yes' then 1 else 0 
		 end )/count(*),2) as discount_rate
from customertrend.customer_behaviour
group by item_purchased
order by discount_rate desc
limit 5;
     

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customertrend.customer_behaviour)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;




-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customertrend.customer_behaviour
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

      
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customertrend.customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customertrend.customer_behaviour
GROUP BY age_group
ORDER BY total_revenue desc;

